### ISSUE TITLE
`mktmpdir` unrecognized

### ISSUE THREAD

**Issue by smackesey** [yuri-karpovich/gemtoabox#2]
This is the first time I've attempted using `gemtoabox`. I get the following error:

$ ❯ gemtoabox \
--gemfile=/Users/smackesey/stm/code/apps/ruby/eratos/Gemfile \
--host=http://localhost:9292 \
--overwrite

Traceback (most recent call last):
	4: from /Users/smackesey/.rbenv/versions/2.5.0/bin/gemtoabox:23:in `<main>'
	3: from /Users/smackesey/.rbenv/versions/2.5.0/bin/gemtoabox:23:in `load'
	2: from /Users/smackesey/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/gemtoabox-0.1.2/exe/gemtoabox:22:in `<top (required)>'
	1: from /Users/smackesey/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/gemtoabox-0.1.2/exe/gemtoabox:22:in `new'
/Users/smackesey/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/gemtoabox-0.1.2/lib/gemtoabox.rb:10:in `initialize': undefined method `mktmpdir' for Dir:Class (NoMethodError)
Did you mean?  mkdir

**Comment by yuri-karpovich** [comment]
Did you pull the latest code? This was fixed in the PR https://github.com/yuri-karpovich/gemtoabox/pull/1

**Comment by banchee** [comment]
Any update to this fix? I am getting the same error with version 0.1.2

**Comment by banchee** [comment]
`root@42c2ed306aa9:/# cat /usr/local/bundle/gems/gemtoabox-0.1.2/lib/gemtoabox.rb`

```
require "gemtoabox/version"
require 'fileutils'

module Gemtoabox
```

tmpdir is not included with the gem when doing gem install gemtoabox.

**Comment by yuri-karpovich** [comment]
@banchee You r right. Sorry for that. Version was bumped to 0.1.3. Please update the gem.
